package com.enhancer.maintenance;

enum CancellationTrustMaintenancePhase {
    AFTER_LOCK_ACQUIRED,
    AFTER_CURRENT_VALIDATED,
    AFTER_CANDIDATE_VALIDATED,
    AFTER_POLICY_CANDIDATE_FORCED,
    AFTER_POLICY_PUBLISHED,
    AFTER_METADATA_CANDIDATE_VALIDATED,
    BEFORE_FINAL_CAS,
    BEFORE_METADATA_SWITCH,
    AFTER_METADATA_SWITCH,
    AFTER_INSTALLED_VERIFIED
}
