package com.enhancer.model;

/** Closed deterministic first-match model candidate rejection reasons. */
public enum ModelCandidateSuitabilityRejectionReason {
    MODEL_CLASS_UNSUPPORTED,
    REQUIRED_CAPABILITY_UNSUPPORTED,
    REASONING_REQUIREMENT_UNSUPPORTED,
    TOKEN_SEMANTICS_UNAVAILABLE,
    CONTEXT_CAPACITY_INSUFFICIENT,
    INPUT_TOKEN_CAPACITY_INSUFFICIENT,
    OUTPUT_TOKEN_CAPACITY_INSUFFICIENT,
    TOTAL_TOKEN_CAPACITY_INSUFFICIENT,
    FREE_ONLY_COST_REQUIRED,
    DATA_CLASSIFICATION_UNSUPPORTED
}
