package com.enhancer.kernel;

public enum VerificationCode {
    VERIFIED,
    TOOL_RESULT_FAILURE,
    REQUEST_RESULT_MISMATCH,
    MISSING_CONTENT_DIGEST,
    MISSING_EVIDENCE,
    EVIDENCE_UNAVAILABLE,
    CORRUPTED_EVIDENCE,
    INVALID_EVIDENCE,
    CONTENT_MISMATCH,
    WORKER_NOT_AWAITING_VERIFICATION
}
